import type { Metadata } from 'next';
import { Ubuntu } from 'next/font/google';
import './globals.css';
import LayoutContainer from '@/components/layout/LayoutContainer';

const ubuntu = Ubuntu({
  subsets: ['latin'],
  variable: '--font-ubuntu',
  weight: ['300', '400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='es'>
      <body
        className={`${ubuntu.variable} bg-white text-black dark:bg-black dark:text-white`}
      >
        <LayoutContainer>
          {children}
        </LayoutContainer>
      </body>
    </html>
  );
}
